// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0-devel
// 	protoc        v4.25.1
// source: drug.proto

package kafkapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdatedDrugByVmedisID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestKey string `protobuf:"bytes,1,opt,name=request_key,json=requestKey,proto3" json:"request_key,omitempty"`
	VmedisId   int64  `protobuf:"varint,2,opt,name=vmedis_id,json=vmedisId,proto3" json:"vmedis_id,omitempty"`
}

func (x *UpdatedDrugByVmedisID) Reset() {
	*x = UpdatedDrugByVmedisID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drug_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatedDrugByVmedisID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatedDrugByVmedisID) ProtoMessage() {}

func (x *UpdatedDrugByVmedisID) ProtoReflect() protoreflect.Message {
	mi := &file_drug_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatedDrugByVmedisID.ProtoReflect.Descriptor instead.
func (*UpdatedDrugByVmedisID) Descriptor() ([]byte, []int) {
	return file_drug_proto_rawDescGZIP(), []int{0}
}

func (x *UpdatedDrugByVmedisID) GetRequestKey() string {
	if x != nil {
		return x.RequestKey
	}
	return ""
}

func (x *UpdatedDrugByVmedisID) GetVmedisId() int64 {
	if x != nil {
		return x.VmedisId
	}
	return 0
}

type UpdatedDrugByVmedisCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestKey string `protobuf:"bytes,1,opt,name=request_key,json=requestKey,proto3" json:"request_key,omitempty"`
	VmedisCode string `protobuf:"bytes,2,opt,name=vmedis_code,json=vmedisCode,proto3" json:"vmedis_code,omitempty"`
}

func (x *UpdatedDrugByVmedisCode) Reset() {
	*x = UpdatedDrugByVmedisCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drug_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatedDrugByVmedisCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatedDrugByVmedisCode) ProtoMessage() {}

func (x *UpdatedDrugByVmedisCode) ProtoReflect() protoreflect.Message {
	mi := &file_drug_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatedDrugByVmedisCode.ProtoReflect.Descriptor instead.
func (*UpdatedDrugByVmedisCode) Descriptor() ([]byte, []int) {
	return file_drug_proto_rawDescGZIP(), []int{1}
}

func (x *UpdatedDrugByVmedisCode) GetRequestKey() string {
	if x != nil {
		return x.RequestKey
	}
	return ""
}

func (x *UpdatedDrugByVmedisCode) GetVmedisCode() string {
	if x != nil {
		return x.VmedisCode
	}
	return ""
}

var File_drug_proto protoreflect.FileDescriptor

var file_drug_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x64, 0x72, 0x75, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x76, 0x6d,
	0x65, 0x64, 0x69, 0x73, 0x22, 0x55, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x44,
	0x72, 0x75, 0x67, 0x42, 0x79, 0x56, 0x6d, 0x65, 0x64, 0x69, 0x73, 0x49, 0x44, 0x12, 0x1f, 0x0a,
	0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x1b,
	0x0a, 0x09, 0x76, 0x6d, 0x65, 0x64, 0x69, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x76, 0x6d, 0x65, 0x64, 0x69, 0x73, 0x49, 0x64, 0x22, 0x5b, 0x0a, 0x17, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x44, 0x72, 0x75, 0x67, 0x42, 0x79, 0x56, 0x6d, 0x65, 0x64,
	0x69, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x76, 0x6d, 0x65, 0x64, 0x69,
	0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x6d,
	0x65, 0x64, 0x69, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x75, 0x72, 0x66, 0x61, 0x61, 0x2f, 0x76, 0x6d,
	0x65, 0x64, 0x69, 0x73, 0x2d, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x6b,
	0x61, 0x66, 0x6b, 0x61, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_drug_proto_rawDescOnce sync.Once
	file_drug_proto_rawDescData = file_drug_proto_rawDesc
)

func file_drug_proto_rawDescGZIP() []byte {
	file_drug_proto_rawDescOnce.Do(func() {
		file_drug_proto_rawDescData = protoimpl.X.CompressGZIP(file_drug_proto_rawDescData)
	})
	return file_drug_proto_rawDescData
}

var file_drug_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_drug_proto_goTypes = []interface{}{
	(*UpdatedDrugByVmedisID)(nil),   // 0: vmedis.UpdatedDrugByVmedisID
	(*UpdatedDrugByVmedisCode)(nil), // 1: vmedis.UpdatedDrugByVmedisCode
}
var file_drug_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_drug_proto_init() }
func file_drug_proto_init() {
	if File_drug_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_drug_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatedDrugByVmedisID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drug_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatedDrugByVmedisCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_drug_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_drug_proto_goTypes,
		DependencyIndexes: file_drug_proto_depIdxs,
		MessageInfos:      file_drug_proto_msgTypes,
	}.Build()
	File_drug_proto = out.File
	file_drug_proto_rawDesc = nil
	file_drug_proto_goTypes = nil
	file_drug_proto_depIdxs = nil
}
